/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type SharedData struct {
	SharedDataId string `json:"sharedDataId"`

	SharedAmData AccessAndMobilitySubscriptionData `json:"sharedAmData,omitempty"`

	SharedSmsSubsData SmsSubscriptionData `json:"sharedSmsSubsData,omitempty"`

	SharedSmsMngSubsData SmsManagementSubscriptionData `json:"sharedSmsMngSubsData,omitempty"`

	SharedDnnConfigurations map[string]DnnConfiguration `json:"sharedDnnConfigurations,omitempty"`

	SharedTraceData *TraceData `json:"sharedTraceData,omitempty"`

	SharedSnssaiInfos map[string]SnssaiInfo `json:"sharedSnssaiInfos,omitempty"`

	SharedVnGroupDatas map[string]VnGroupData `json:"sharedVnGroupDatas,omitempty"`
}
